services:
  frontend:
    image: node:18.18.2-bullseye
    container_name: frontend
    restart: always
    environment:
      - NEXT_PUBLIC_BACK_END_BASE_URL=http://localhost:8080
    volumes:
      - ./app:/app/app
      - ./docker/development:/app/scripts
      - ./public/:/app/public
      - ./.eslintrc.json:/app/.eslintrc.json
      - ./middleware.ts:/app/middleware.ts
      - ./next-env.d.ts:/app/next-env.d.ts
      - ./next.config.js:/app/next.config.js
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
      - ./tsconfig.next.json:/app/tsconfig.next.json
      - ./.next:/app/.next
      - ./node_modules:/app/node_modules
    command: >
      /bin/sh -c '\
        apt-get update && \
        apt-get install -y findutils wget openssl inotify-tools dos2unix && \
        if [ ! -e /bin/dockerize ]; then \
          wget -O - https://github.com/jwilder/dockerize/releases/download/v0.7.0/dockerize-linux-amd64-v0.7.0.tar.gz | tar xzf - -C /bin; \
        fi && \
        find /app/scripts -type f -name "*.sh" -exec dos2unix {} \; && \
        chmod +x /app/scripts/*.sh && \
        /app/scripts/config_dev_env.sh && \
        /app/scripts/dev.sh'
    ports:
      - 3000:3000