services:
  database:
    image: lordluch/gamix-database
    container_name: database
    volumes:
      - pg_data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - gamix_network
  backend:
    image: lordluch/gamix-back-end
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SIGNING_KEY_SECRET=Graphql
      - FRONT_END_BASE_URL=http://localhost:3000
    networks:
      - gamix_network
    depends_on:
      - database
    links:
      - database
  frontend:
    build: .
    image: lordluch/gamix-front-end
    container_name: frontend
    restart: always
    environment:
      - NEXT_PUBLIC_BACK_END_BASE_URL=http://localhost:8080
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  pg_data:

networks:
  gamix_network:
    driver: bridge