export const apiErrors: string[] = [
  "INVALID_ACCESS_TOKEN",
  "INVALID_REFRESH_TOKEN",
  "NULL_JWT_TOKENS",
  "TOKEN_CLAIMS_EXCEPTION",
  "TOKEN_DO_NOT_MATCH_EXCEPTION",
  "EXCESSIVE_FAILED_LOGIN_ATTEMPTS",

  "USER_NOT_FOUND",
  "PASSWORDUSER_NOT_FOUND",
  "PASSWORDUSER_ALREADY_EXISTS",

  "USERNAME_EMPTY",
  "USERNAME_NULL",
  "USERNAME_TOO_LONG",
  "USERNAME_TOO_SHORT",
  "USERNAME_INVALID_FORMAT",

  "EMAIL_EMPTY",
  "EMAIL_NULL",
  "EMAIL_TOO_LONG",
  "EMAIL_TOO_SHORT",
  "EMAIL_INVALID_FORMAT",
  "EMAIL_ALREADY_VERIFIED",

  "PASSWORD_WRONG",
  "PASSWORD_NULL",
  "PASSWORD_INVALID_FORMAT",
  "PASSWORD_TOO_SHORT",
  "PASSWORD_TOO_LONG",
  "PASSWORD_MISSING_SPECIAL_CHAR",
  "PASSWORD_MISSING_NUMBER",
  "PASSWORD_MISSING_UPPERCASE",

  "USER_ALREADY_EXISTS_WITH_THIS_USERNAME",
  "USER_ALREADY_EXISTS_WITH_THIS_EMAIL",
  "USER_NOT_FOUND_BY_TOKEN",
  "USER_NOT_FOUND_BY_EMAIL",
  "USER_NOT_FOUND_BY_USERNAME",
  "USER_NOT_FOUND_BY_ID",

  "USER_PROFILE_NOT_FOUND",

  "POST_NOT_FOUND_BY_ID",
  "POST_NOT_FOUND_BY_TITLE",
  "COMPLETELY_EMPTY_POST",
  "TITLE_TOO_LONG",
  "CONTENT_TOO_LONG",
  "TOO_MANY_LINKS",
  "TOO_MANY_IMAGES",

  "INVALID_ID"
];

